@startuml

skinparam dpi 250
hide empty members

Device "1" *- "1" DeviceCapabilities
DeviceCapabilities <|- AbstractExecutionContext
NetworkManager "1" --* "1" DeviceCapabilities
abstract class AbstractExecutionContext
interface NetworkManager
@enduml