@startuml

skinparam dpi 250
hide empty members

Device "1" o- "1" NetworkManager : use
NetworkManager <|.. MqttNetworkManager
interface NetworkManager <<Interface>> {
  +shareState(Map<CodePath, Object>) : void
  +getNeighborState() : Map<DeviceUID, Map<CodePath, Object>>
}

class MqttNetworkManager {
  -neighbors: List<String>
  +listen(): void
  +stop(): void
}
note left
""listen()"" e ""stop()"" consentono di
avviare e fermare l'ascolto al broker
di messaggistica.
""neighbors"" è una lista di //topic//,
uno per ogni dispositivo vicino.
end note

class Device {
  +getNetworkManager() : NetworkManager
}

@enduml