@startuml

skinparam dpi 250
hide empty members

NetworkManager -o AbstractExecutionContext : features
ProtelisVM o- ExecutionContext : uses
ExecutionContext <|.. AbstractExecutionContext
interface NetworkManager
interface ExecutionContext
abstract class AbstractExecutionContext
@enduml