@startuml

skinparam dpi 250
hide empty members

ProtelisVM "1" o-- "1" ExecutionContext : uses
ProtelisVM "1" o- "1" ProtelisProgram : executes
interface ExecutionContext
interface ProtelisProgram
class ProtelisVM
@enduml
